--readFilesCommand: zcat
--readNameSeparator: "'|'"
--limitBAMsortRAM: 48000000000
--outReadsUnmapped: Fastx
--outSAMtype: "BAM SortedByCoordinate"
--quantMode: TranscriptomeSAM
--outSAMattributes: All
--outSAMstrandField: intronMotif
--outSAMheaderHD: "'@HD: VN:1.4: SO:coordinate'"
--outSAMunmapped: Within
--runThreadN: 4
--runRNGseed: 777
