--readFilesCommand: zcat
--readNameSeparator: "'|'"
--limitBAMsortRAM: 48000000000
--outReadsUnmapped: Fastx
--outSAMtype: "BAM SortedByCoordinate"
--quantMode: TranscriptomeSAM
--outSAMattributes: All
--outSAMstrandField: intronMotif
--outSAMheaderHD: "'@HD: VN:1.4: SO:coordinate'"
--limitOutSJcollapsed: 1000000
--limitSjdbInsertNsj: 1000000
--outFilterMultimapNmax: 100
--outFilterMismatchNmax: 33
--outFilterMismatchNoverLmax: 0.3
--seedSearchStartLmax: 12
--alignSJoverhangMin: 15
--alignEndsType: Local
--outFilterMatchNminOverLread: 0
--outFilterScoreMinOverLread: 0.3
--winAnchorMultimapNmax: 50
--alignSJDBoverhangMin: 3
--outFilterType: BySJout
--runThreadN: 4
--runRNGseed: 777
