grch38:
  gencode:
    --gtf: ${MH_APP_SHARED}/assets/references/grch38/annotations/gencode/gencode.v31.annotation.gtf
    --tophat2-index: ${MH_APP_SHARED}/assets/references/grch38/indexes/bowtie2/GRCh38.primary_assembly.genome
    --hisat2-index: ${MH_APP_SHARED}/assets/references/grch38/indexes/hisat2/GRCh38.primary_assembly.genome.gencode.v31.annotation
    --star-index: ${MH_APP_SHARED}/assets/references/grch38/indexes/star/GRCh38.primary_assembly.genome.gencode.v31.annotation
    --kallisto-index: ${MH_APP_SHARED}/assets/references/grch38/indexes/kallisto/gencode.v31.transcripts.formatted
    --rsem-index: ${MH_APP_SHARED}/assets/references/grch38/indexes/rsem/gencode.v31.transcripts.formatted
    --ebseq-ngvector: ${MH_APP_SHARED}/assets/references/grch38/indexes/ebseq/gencode.v31.transcripts.formatted.ngvec
  refseq:
    --gtf: ${MH_APP_SHARED}/assets/references/grch38/annotations/refseq/GCF_000001405.39_GRCh38.p13_genomic.formatted.gtf
    --star-index: ${MH_APP_SHARED}/assets/references/grch38/indexes/star/GRCh38.primary_assembly.genome.GCF_000001405.39_GRCh38.p13_genomic.formatted
    --rsem-index: ${MH_APP_SHARED}/assets/references/grch38/indexes/rsem/GCF_000001405.39_GRCh38.p13_transcripts.formatted
    --ebseq-ngvector: ${MH_APP_SHARED}/assets/references/grch38/indexes/ebseq/GCF_000001405.39_GRCh38.p13_transcripts.formatted.ngvec
  noncode:
    --gtf: ${MH_APP_SHARED}/assets/references/grch38/annotations/noncode/NONCODEv5_hg38.lncAndGene_formatted.gtf
    --star-index: ${MH_APP_SHARED}/assets/references/grch38/indexes/star/GRCh38.primary_assembly.genome.NONCODEv5_hg38.lncAndGene_formatted
    --rsem-index: ${MH_APP_SHARED}/assets/references/grch38/indexes/rsem/NONCODEv5_human_transcripts_formatted
    --ebseq-ngvector: ${MH_APP_SHARED}/assets/references/grch38/indexes/ebseq/NONCODEv5_human_transcripts_formatted.ngvec
